In [1]:
import numpy as np 

In [2]:
x = np.linspace(0, 1, 100)

In [3]:
x 

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [7]:
y = np.random.randn(100)

In [8]:
y

array([ 4.72418213e-01,  5.80366997e-01, -5.19583128e-01, -1.52980627e+00,
        6.27425476e-01,  3.75756593e-01, -2.09928676e-01,  1.27996383e-01,
        1.57735583e+00,  1.57215418e-01, -2.04061929e+00, -1.21739201e+00,
        1.10735752e+00,  3.78342569e-02,  4.90993703e-01, -1.85826299e+00,
        1.05108019e+00, -9.08190507e-01, -7.24742489e-01, -1.74351795e+00,
        1.52746081e-01, -1.74227355e+00,  3.49596946e-02, -9.93778455e-01,
       -1.66311335e-03, -1.40044125e+00,  4.09159533e-01,  2.95117961e-01,
       -6.06941737e-01, -9.09070754e-01,  2.42843611e-01,  3.21310086e-01,
       -3.78512665e-01, -1.79591846e-01, -1.05048346e+00,  1.52478284e+00,
       -2.37130071e+00, -4.31800806e-01, -1.61473138e+00,  5.85326175e-01,
       -8.27275584e-01, -1.09217489e+00, -4.74992192e-01,  2.84699012e-01,
       -8.07752794e-01, -1.12705876e-01,  8.30570504e-01, -1.52530139e+00,
       -4.72465129e-01,  6.68070914e-01,  8.90891412e-03,  1.03045216e+00,
       -3.57373810e-01,  

In [9]:
a = np.random.randint(0,10,(3,3))
print(a)

[[8 4 7]
 [2 4 4]
 [2 7 3]]


In [10]:
import plotly.offline as pyo
import plotly.graph_objs as go

In [12]:
trace0 = go.Scatter(x=x, y=y+5, mode='markers', name='markers')
trace1 = go.Scatter(x=x, y=y, mode='lines', name='lines')
trace2 = go.Scatter(x=x, y=y-5, mode='lines+markers', name='lines+markers')
data = [trace0, trace1, trace2]
layout = go.Layout(title='sample')
fig = go.Figure(data, layout)
pyo.plot(fig, 'sample.html')

'temp-plot.html'

In [13]:
#######
# This line chart displays the same data
# three different ways along the y-axis.
######
import plotly.offline as pyo
import plotly.graph_objs as go
import numpy as np

np.random.seed(56)
x_values = np.linspace(0, 1, 100) # 100 evenly spaced values
y_values = np.random.randn(100)   # 100 random values

# create traces
trace0 = go.Scatter(
    x = x_values,
    y = y_values+5,
    mode = 'markers',
    name = 'markers'
)
trace1 = go.Scatter(
    x = x_values,
    y = y_values,
    mode = 'lines+markers',
    name = 'lines+markers'
)
trace2 = go.Scatter(
    x = x_values,
    y = y_values-5,
    mode = 'lines',
    name = 'lines'
)
data = [trace0, trace1, trace2]  # assign traces to data
layout = go.Layout(
    title = 'Line chart showing three different modes'
)
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig, filename='line1.html')


'line1.html'

In [15]:
import pandas as pd 
# read a .csv file into a pandas DataFrame:
df = pd.read_csv('c:/Users/LENOVO/Desktop/population.csv', index_col=0)


In [16]:
df

PopEstimate2010  PopEstimate2011  PopEstimate2012  \
Name                                                               
Connecticut            3580171          3591927          3597705   
Maine                  1327568          1327968          1328101   
Massachusetts          6564943          6612178          6659627   
New Hampshire          1316700          1318345          1320923   
Rhode Island           1053169          1052154          1052761   
Vermont                 625842           626210           625606   

               PopEstimate2013  PopEstimate2014  PopEstimate2015  \
Name                                                               
Connecticut            3602470          3600188          3593862   
Maine                  1327975          1328903          1327787   
Massachusetts          6711138          6757925          6794002   
New Hampshire          1322622          1328684          1330134   
Rhode Island           1052784          1054782          1055916   
Vermont                 626044           625665           624455   

               PopEstimate2016  PopEstimate2017  
Name                                             
Connecticut            3587685          3588184  
Maine                  1330232          1335907  
Massachusetts          6823721          6859819  
New Hampshire          1335015          1342795  
Rhode Island           1057566          1059639  
Vermont                 623354           623657

In [17]:
# create traces
traces = [go.Scatter(
    x = df.columns,
    y = df.loc[name],
    mode = 'markers+lines',
    name = name
) for name in df.index]

layout = go.Layout(
    title = 'Population Estimates of the Six New England States'
)

fig = go.Figure(data=traces,layout=layout)
pyo.plot(fig, filename='line2.html')

'line2.html'

In [18]:
x = df.columns

In [19]:
x 

Index(['PopEstimate2010', 'PopEstimate2011', 'PopEstimate2012',
       'PopEstimate2013', 'PopEstimate2014', 'PopEstimate2015',
       'PopEstimate2016', 'PopEstimate2017'],
      dtype='object')

In [24]:
df.loc[df.index]


PopEstimate2010  PopEstimate2011  PopEstimate2012  \
Name                                                               
Connecticut            3580171          3591927          3597705   
Maine                  1327568          1327968          1328101   
Massachusetts          6564943          6612178          6659627   
New Hampshire          1316700          1318345          1320923   
Rhode Island           1053169          1052154          1052761   
Vermont                 625842           626210           625606   

               PopEstimate2013  PopEstimate2014  PopEstimate2015  \
Name                                                               
Connecticut            3602470          3600188          3593862   
Maine                  1327975          1328903          1327787   
Massachusetts          6711138          6757925          6794002   
New Hampshire          1322622          1328684          1330134   
Rhode Island           1052784          1054782          1055916   
Vermont                 626044           625665           624455   

               PopEstimate2016  PopEstimate2017  
Name                                             
Connecticut            3587685          3588184  
Maine                  1330232          1335907  
Massachusetts          6823721          6859819  
New Hampshire          1335015          1342795  
Rhode Island           1057566          1059639  
Vermont                 623354           623657